/**
 * The Terms & Conditions a dealer agrees to when registering from the app.
 *
 * COPIED, WORD FOR WORD, FROM THE WEBSITE'S ENROLMENT PAGE
 * (`mdg-landing/src/i18n/{en,hi}/register.ts`), which in turn copies the ten
 * clauses of the signed service agreement. The app and the website send the
 * same form to the same inbox, so a dealer must be agreeing to the same text
 * whichever one they used: change a clause there and here in the same pass.
 *
 * The English list is the binding one. The Hindi list is a courtesy
 * translation, so the sheet says so and offers the English original.
 */
export const TERMS_EN: readonly string[] = [
  'The Dealer shall share the User ID and the Password to the Service Provider for carrying out services, as mutually agreed. The list of services as well as respective charges/rates for the services provided by the Service Provider to the Dealer is illustrated in Annexure-I. Any services outside the scope of Annexure-I shall be mutually negotiated between the Parties.',
  'Parties agree to maintain confidentiality of the data/information disclosed to each other. Party receiving such Confidential Information shall not disclose this information without the prior written consent of the Disclosing Party.',
  'Service Provider shall provide all the services to the Dealer virtually only (Online services). However, upon urgent request of the Dealer, onsite services shall be provided by the Service Provider subject to the availability of manpower as well as accessibility of the Dealer\'s Location. Cost for providing such services physically at the location of the Dealer shall be mutually negotiated between the Parties.',
  'It is acknowledged and confirmed by the Dealer that Service Provider is fully dependent on the Dealer in respect of the data/information/documents required for providing services to the Dealer. It is further acknowledged and confirmed by the Dealer that the Service Provider has no mechanism to check the authenticity/accuracy of such data/information/documents, and therefore Service Provider shall not be responsible for any deficiency in services on account of wrong/incorrect data/information/documents provided by the Dealer to the Service Provider.',
  'It is agreed between the Parties that since the services are being provided by the Service Provider virtually therefore in the event of any delay/deficiency of services on account of poor internet network, dealer\'s non-cooperation, non-availability of the spare parts, and other FORCE MAJEURE events including flood, Strike, Lock down, Earthquake, Government Holidays, riots etc, Service Provider shall not be liable for fine/penalty which might be imposed on the Dealer for non-compliance/delayed compliance/failure to comply with PESO/OMC/Government regulations/guidelines.',
  'It is acknowledged and confirmed by the Dealer that all the services being carried out by the Service Provider is, for and on behalf of the Dealer, and the Service Provider shall be acting as an independent Consultant, and therefore Service Provider shall not be responsible for any acts or failure of the Dealer to follow the PESO/OMC/Government regulations/guidelines.',
  'Dealer shall make all the payment to the Service Provider through Bank Transfer/UPI Transfer or in any manner as agreed between the Parties. Service Provider shall add applicable GST charges and raise invoice in the name of the Dealer. Payment shall be made within 10 days of receipt of the invoice. Any delay beyond this period shall entitle the Service Provider to charge interest @ 18% per annum.',
  'Dealer agrees to defend and indemnify the Service Provider against all suits, actions, penalties and liabilities that may arise from failure on the part of the Dealer to comply regulatory provisions/statutory guidelines as notified by OMC/PESO/Government Authorities from time to time.',
  'This agreement shall remain valid for a period of 1 year from the Signing Date, and may further be renewed for successive terms of 1 (One) year each unless terminated by Parties with prior 30 days written notice to the other Party. However, Service Provider shall be entitled to terminate this Agreement immediately in the event of non-receipt of the payment within the period/timeline stipulated in the invoice.',
  'Parties agree that all the disputes related to the services provided by the Service Provider under this agreement shall be the exclusive jurisdiction of Courts at Delhi.',
];

export const TERMS_HI: readonly string[] = [
  'सेवाएँ करने के लिए डीलर अपनी User ID और Password सेवा प्रदाता (Service Provider) को देगा, जैसा दोनों के बीच तय हुआ है। सेवा प्रदाता डीलर को जो सेवाएँ देगा और उनके लिए जो शुल्क या दरें (charges/rates) लगेंगी, उनकी सूची Annexure-I में दी गई है। Annexure-I से बाहर की किसी भी सेवा पर दोनों पक्ष (Parties) आपस में बात करके तय करेंगे।',
  'दोनों पक्ष इस बात पर सहमत हैं कि एक-दूसरे को दिए गए डेटा और जानकारी को गोपनीय रखेंगे। जिस पक्ष को ऐसी गोपनीय जानकारी (Confidential Information) मिलती है, वह उसे देने वाले पक्ष (Disclosing Party) की पहले से ली गई लिखित मंज़ूरी के बिना किसी को नहीं बताएगा।',
  'सेवा प्रदाता डीलर को सारी सेवाएँ सिर्फ़ ऑनलाइन ही देगा। लेकिन डीलर के ज़रूरी अनुरोध पर सेवा प्रदाता मौके पर आकर भी सेवा दे सकता है, बशर्ते उस समय आदमी उपलब्ध हों और डीलर की जगह तक पहुँचा जा सके। मौके पर आकर सेवा देने का ख़र्च दोनों पक्ष आपस में बात करके तय करेंगे।',
  'डीलर यह मानता है और पुष्टि करता है कि सेवाएँ देने के लिए जो डेटा, जानकारी और काग़ज़ात चाहिए, उनके लिए सेवा प्रदाता पूरी तरह डीलर पर निर्भर है। डीलर यह भी मानता है और पुष्टि करता है कि ऐसे डेटा, जानकारी और काग़ज़ात के सही और असली होने की जाँच करने का कोई तरीक़ा सेवा प्रदाता के पास नहीं है, इसलिए डीलर की ओर से दिए गए ग़लत डेटा, जानकारी या काग़ज़ात की वजह से सेवा में कोई कमी रह जाए, तो उसके लिए सेवा प्रदाता ज़िम्मेदार नहीं होगा।',
  'दोनों पक्षों के बीच यह तय हुआ है कि सेवाएँ ऑनलाइन दी जा रही हैं, इसलिए इंटरनेट नेटवर्क ख़राब होने, डीलर की ओर से सहयोग न मिलने, स्पेयर पार्ट्स उपलब्ध न होने, या बाढ़, हड़ताल, लॉकडाउन, भूकंप, सरकारी छुट्टी, दंगे जैसी दैवी आपदा (FORCE MAJEURE) की वजह से सेवा में देरी या कमी होती है, तो PESO, OMC या सरकारी नियमों और दिशा-निर्देशों का पालन न होने, देर से होने या पूरा न होने पर डीलर पर जो जुर्माना (fine/penalty) लगे, उसके लिए सेवा प्रदाता ज़िम्मेदार नहीं होगा।',
  'डीलर यह मानता है और पुष्टि करता है कि सेवा प्रदाता जो भी काम करता है, वह डीलर की ओर से और डीलर के लिए करता है, और इसमें सेवा प्रदाता एक स्वतंत्र सलाहकार (independent Consultant) के तौर पर काम करता है। इसलिए PESO, OMC या सरकारी नियमों और दिशा-निर्देशों का पालन करने में डीलर से जो भी चूक या ग़लती हो, उसके लिए सेवा प्रदाता ज़िम्मेदार नहीं होगा।',
  'डीलर सारा भुगतान सेवा प्रदाता को बैंक ट्रांसफ़र या UPI ट्रांसफ़र से करेगा, या उस तरीक़े से जो दोनों पक्षों के बीच तय हो। सेवा प्रदाता उस पर लागू GST जोड़कर डीलर के नाम से इनवॉइस बनाएगा। भुगतान इनवॉइस मिलने के 10 दिन के भीतर करना होगा। इससे ज़्यादा देर होने पर सेवा प्रदाता 18% सालाना की दर से ब्याज लगा सकता है।',
  'OMC, PESO या सरकारी विभाग समय-समय पर जो नियम और दिशा-निर्देश जारी करते हैं, उनका पालन डीलर की ओर से न होने पर जो भी मुक़दमे, कार्रवाई, जुर्माने और देनदारियाँ आएँ, उनमें डीलर सेवा प्रदाता का बचाव करेगा और उसका पूरा नुक़सान भरेगा (defend and indemnify)।',
  'यह समझौता साइन होने की तारीख़ से 1 साल तक चलेगा, और आगे भी 1-1 साल के लिए बढ़ता रहेगा, जब तक कोई पक्ष दूसरे पक्ष को 30 दिन पहले लिखित सूचना देकर इसे ख़त्म न कर दे। लेकिन अगर इनवॉइस में लिखी अवधि के भीतर भुगतान नहीं मिलता, तो सेवा प्रदाता इस समझौते को तुरंत ख़त्म कर सकता है।',
  'दोनों पक्ष सहमत हैं कि इस समझौते के तहत सेवा प्रदाता की दी गई सेवाओं से जुड़े सभी विवाद सिर्फ़ दिल्ली की अदालतों के अधिकार क्षेत्र (exclusive jurisdiction) में आएँगे।',
];
